import turtle
t = turtle
t. Screen()
t. bgcolor("#3895D3")
t. color("#ff0000")
t. pensize(50)
t. penup()
t. hideturtle()
t. speed(0)
t. setposition(-100, 100)
t. pendown()
t. setposition(100, 100)
t. penup()
t. setposition(0, 75)
t. color("#ffffff")
t. write("Play", align= "center", font=("Arial", 32, "normal"))
t. done()